

# Autogenerated from package.yaml; do not edit directly.




{
  description = ''Bindings for the Gumbo HTML5 parsing library'';
  inputs.flake-utils.url = "github:numtide/flake-utils";

  outputs = inputs@{ self, nixpkgs, flake-utils, ... }:
    flake-utils.lib.eachSystem [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" ] (system:
      let
        overlays = [ ];
        pkgs = import nixpkgs { inherit system overlays;  };
        
        make = isDev:
           let hs = pkgs.haskellPackages; in
          hs.developPackage {
            name = "gumbo";
            root = ./.;
            withHoogle = false;
            returnShellEnv = isDev;
            
            modifier = drv: pkgs.haskell.lib.addBuildTools drv
              [
                hs.cabal-fmt
                hs.cabal-install
                hs.ghcid
                hs.haskell-language-server
                hs.ormolu
                
              ];
          };
      in
      {
        defaultPackage = make false;
        devShell = make true;
      });
}
